### ISSUE TITLE
Common header and rules for scripts/functions

### ISSUE THREAD

**Issue by liocarcinus** [ices-eg/WKSSFGEO#8]
After looking at the new very much appreciated github structure, I think we should have some rules to have all files organised. 
What do you think if we make some organisation rules like, for example: 
1. All functions & scripts submitted should have the author's 2 initials on it's name (this way we can immediately spot)
2. All functions & scripts should have minimum header with information on title, use, author/origin, etc.

Should we make the functions as much as possible to add a column with the classification as a return and not a new table with filtered results (like we spoke on the meeting)? Not sure if this was clear...

**Comment by einarhjorleifsson** [comment]
on point 1: sound like a plan - i actually use the prefix rb_, see R-dev/einar/ramb_functions2.R. store them there because i still need to check how stable they are (lots of purrring), if they work on other datasets than mendo 2019 and how well they scale when when confronted with "big" data.
on point 2: will try my best
on last point: agree, already spent some time working towards that aim.

**Comment by einarhjorleifsson** [comment]
think this can be closed
